### ISSUE TITLE
Manque les polices?

### ISSUE THREAD

**Issue by nhuhoai** [NicHub/fontawesome-local#1]
Hello,

Je crois qu'il te manque les polices en local. Tu peux te baser sur les serveurs CDN par exemple sur:
https://cdnjs.com/libraries/font-awesome

**Comment by NicHub** [comment]
Hello et merci pour ton commentaire. Je vois que Rolf a fait de la pub pour cet exemple qui lui était destiné à la base. ;-)

Sinon pour répondre à ton commentaire : les liens CDN que tu proposes correspondent à l’ancienne façon d’intégrer les icônes Font Awesome qui se basait sur des fichiers CSS + des fichiers SVG distincts. Aujourd’hui Font Awesome propose une solution où toutes les informations sont incluses dans un fichier JavaScript unique.

Quand on travaille avec l’ESP8266 qui a très peu de ressources, c’est peut-être plus facile de travailler avec l’ancienne façon, car on peut inclure uniquement les fichiers SVG qui nous intéressent et je suppose que c’est ce à quoi tu pensais en m’envoyant les liens vers leur CDN.

Dans cet exemple, je me suis pris au jeu et j’ai essayé la méthode 100% JS et c’est celle que j’ai proposée à Rolf.

**Comment by nhuhoai** [comment]
Ahh sympa d'intégrer tout en un, je pense qu'ils sont passé au format SVG directement. Je n'avais pas vu qu'ils sont passé à la release suivante en effet ;)

Si tu cherches l'optimisation en taille, je te conseille de faire un saut ici: https://tagliala.github.io/vectoriconsroundup/ (ils n'ont pas encore mise à jour pour FontAwesome).

Je pense que tu as remarqué dans les exemples de l'esp mais le webserver autorise la compression gunzip des fichiers sources afin de réduire encore plus la taille. Belle soirée à toi!
